Adding s3 storage feature #102
tsdat/tsdat pull request #106
Opened 2022-08-04 07:09 UTC by kefeimo

adding new features for issue #102 
- Implemented S3Storage class with (public interface) methods
  - save_data_s3
  - fetch_data_s3
  - save_ancillary_file_s3
- with associated tests
  - test_filesystem_save_and_fetch_data_s3
  - test_filesystem_saves_ancillary_files_s3
- Updated dependency requirement.txt
- Hotfix of assert_close

Note:
Watch closely for environment setting for AWS credentials, i.e.
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_SESSION_TOKEN

TODO
(maybe) create end-to-end example for pipeline with s3 storage (counterpart of [test_pipeline.py](https://github.com/tsdat/tsdat/blob/main/test/pipeline/test_pipeline.py))

2022-08-08 19:08 UTC, maxwellevin requested changes
Changes requested to keep APIs consistent with other storage classes, but other than that it looks good. I'll work on these changes today.

2022-08-08 19:08 UTC, maxwellevin commented on tsdat/io/storage.py
> +    def save_data_s3(self, dataset: xr.Dataset):
The same goes for the other public methods

2022-08-08 19:08 UTC, maxwellevin commented
We also need the tests to pass. This is likely just due to some environment settings I need to update

2022-08-08 19:35 UTC, kefeimo commented
temporarily close to update

2022-08-08 20:04 UTC, kefeimo commented on tsdat/io/storage.py
> +    def save_ancillary_file(self, filepath: Path, datastream: str):
Note: I will keep the signature type consistent, i.e., filepath: Path, but this might not be appropriate on S3, because S3 path is just a string

2022-08-08 20:19 UTC, maxwellevin commented
@kefeimo I can work on these changes

2022-08-08 20:34 UTC, kefeimo commented
> @kefeimo I can work on these changes

Opps. I just resolved request changes except "This can be implemented as a pydantic root_validator ". I will let you take over from there. Thank you.

2022-08-10 01:00 UTC, maxwellevin approved these changes

2022-08-10 01:08 UTC, maxwellevin commented
Tests are passing locally using my AWS credentials and with python 3.10. Now I need to make sure it works with the dummy user/credentials for our tsdat account

2022-08-25 16:36 UTC, maxwellevin commented
99% certain that the tsdat AWS creds are configured correctly, but I just learned that PRs from other repos do not have access to repository secrets in the target repo. This explains why the tests keep failing here.

Merging this and will debug in tsdat if I have to.

2022-08-25 16:37 UTC, merged