Incorporate ACDD and IOOS standards
tsdat/tsdat pull request #139
Opened 2023-07-21 16:55 UTC by jmcvey3

TODO:

- [ ] Create VsCode schema
- [ ] Add standards options to cookiecutter to generate keywords in "dataset.yaml" automatically

2023-07-21 16:56 UTC, jmcvey3 commented
Issue #132

2023-10-10 18:37 UTC, maxwelllevin requested changes
Minor changes requested for type hints. Everything else looks great.

2023-10-10 18:37 UTC, maxwelllevin commented on pyproject.toml
> +  "moto",
Is `moto` a runtime dependency? I.e., needed to use certain features of tsdat? Or is it just needed for development purposes? I ask bc it's already included as an optional dependency in the `[project.optional-dependencies]` --> `dev` section (ie. `pip install ".[dev]"` would include it)

2023-10-10 18:37 UTC, maxwelllevin commented on tsdat/config/variables.py
> +    )
Can you make the type hint for these `Optional[str]` / `Optional[float]` since these are optional attributes and default to `None`?

2023-10-10 18:37 UTC, maxwelllevin commented on tsdat/pipeline/pipelines.py
> +    def tmp_dir(self) -> Path:
Likewise here: `Optional[xr.Dataset]` and `Optional[Path]`. This is to make `mypy` happy since the default is `None`.

2023-10-10 21:22 UTC, maxwelllevin approved these changes
Requested changes addressed. Everything looks good

2023-10-11 23:36 UTC, maxwelllevin commented
@jmcvey3 merge at-will

2023-10-11 23:53 UTC, merged